rule('shaders')
    set_extensions('.fs', '.vs', '.glsl')
    on_build_files(function(target, filepatch, opt)
        import('copy_file', {alias = 'utils'})
        local targetPath = path.join(utils.kbuildBaseFolder(), 'shaders')
        utils.kcopyFiles(targetPath, filepatch.sourcefiles)
    end)
rule_end()

rule('textures')
    set_extensions('.png')
    on_build_files(function(target, filepatch, opt)
        import('copy_file', {alias = 'utils'})
        local targetPath = path.join(utils.kbuildBaseFolder(), 'textures')
        utils.kcopyFiles(targetPath, filepatch.sourcefiles)
    end)
rule_end()

target('shaders')
    set_kind('object')
    add_rules('shaders')
    add_files('**.fs', './**/**.fs', '**.vs', './**/**.vs')

target('textures')
    set_kind('object')
    add_rules('textures')
    add_files('**.png', './**/**.png')

target('resources')
    set_kind('phony')
    add_deps('textures', 'shaders')